version: '3'
services:
  blog:
    image:  wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on: 
      - database
    restart: always
    networks:
      - my-network  



  database:
    image:  mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

    volumes:
      - "meudbdata:/var/lib/mysql"
    restart: always
    networks:
      - my-network 

volumes:
  meudbdata:

networks:
  my-network:
