version: '3'

services:
  frontend:
    build: ./frontend
    ports:
     - "8080:3000"
    networks:
      - backend
    depends_on:
      - api
  
  api:
    build: ./backend
    networks:
      - backend
    ports:
      - "3000:3000"

networks:
  backend:
    driver: bridge  